### ISSUE TITLE
serialize unexpected length in Dump

### ISSUE THREAD

**Issue by weiliu1031** [greatroar/blobloom#9]
i wonder to know why we serialize `len(b)-1)` in `dump` and use `1 + uint64(binary.LittleEndian.Uint32(l.buf[12:]))`
 in `newLoader`? 
 
![image](https://github.com/greatroar/blobloom/assets/108661493/af31f406-9113-4c89-a016-e705dd5e05ba)
![image](https://github.com/greatroar/blobloom/assets/108661493/67720075-9592-4b32-a282-e78a8bb6823c)

**Comment by greatroar** [comment]
The number of blocks is at least one. Storing one less than the actual number allows 2³² blocks, whereas storing the actual number would allow only 2³²-1. I admit this is kind of tricky and I should add a comment to explain it.
